"""Add table

Revision ID: 05ac28896fcf
Revises: 14cc6afc0640
Create Date: 2025-08-26 10:37:20.147847

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05ac28896fcf"
down_revision: Union[str, Sequence[str], None] = "14cc6afc0640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ranks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "posts", ["id"])
    op.add_column("users", sa.Column("rank_id", sa.Integer(), nullable=False))
    op.alter_column(
        "users", "post_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "users", "ranks", ["rank_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.alter_column(
        "users", "post_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("users", "rank_id")
    op.drop_constraint(None, "posts", type_="unique")
    op.drop_table("ranks")
    # ### end Alembic commands ###
