"""Add field username table

Revision ID: 78258f2c8b8c
Revises: 05ac28896fcf
Create Date: 2025-08-26 10:57:24.998553

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78258f2c8b8c"
down_revision: Union[str, Sequence[str], None] = "05ac28896fcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "ranks", ["id"])
    op.add_column(
        "users", sa.Column("username", sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.drop_constraint(None, "ranks", type_="unique")
    # ### end Alembic commands ###
