"""Add field photo and phone to user table

Revision ID: f6b6fc7b847b
Revises: dba1f95034d8
Create Date: 2025-08-27 16:23:57.592608

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6b6fc7b847b"
down_revision: Union[str, Sequence[str], None] = "dba1f95034d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("nickname", sa.String(length=50), nullable=True)
    )
    op.add_column("users", sa.Column("photo", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("personnel_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "personnel_number")
    op.drop_column("users", "phone")
    op.drop_column("users", "photo")
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
